CREATE TABLE `duizhang_dljh_lst` (
  `id` varchar(32) NOT NULL,
  `reqSysStance` varchar(6) DEFAULT NULL,
  `reqTime` varchar(20) NOT NULL,
  `outAccount` char(19) NOT NULL,
  `tradeAmount` char(12) NOT NULL,
  `tradeFee` varchar(12) DEFAULT NULL,
  `termId` varchar(8) NOT NULL,
  `merCode` varchar(16) NOT NULL,
  `deductSysReference` varchar(12) DEFAULT NULL,
  `authorizationCode` varchar(6) DEFAULT NULL,
  `whetherErroeHandle` int(11) NOT NULL DEFAULT '0',
  `dz_file_name` varchar(100) NOT NULL,
  `inst_name` varchar(64) NOT NULL,
  `bk_chk` int(11) NOT NULL DEFAULT '0',
  `deduct_stlm_date` varchar(20) NOT NULL,
  `settleAmount` char(12) NOT NULL,
  `origDeductSysReference` varchar(12) DEFAULT NULL,
  `batch_no` char(6) DEFAULT NULL,
  `mer_name` varchar(128) DEFAULT NULL,
  `msgType` char(4) DEFAULT NULL,
  `process` varchar(6) DEFAULT NULL,
  `origDataStance` char(6) DEFAULT NULL,
  `accountName` varchar(128) DEFAULT NULL,
  `accountBank` varchar(128) DEFAULT NULL,
  `accountType` char(2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

