DROP TABLE IF EXISTS `duizhang_yl_wap_lst`;
CREATE TABLE `duizhang_yl_wap_lst` (
  `id` varchar(32) NOT NULL,
  `tradingNo` varchar(32) DEFAULT NULL,
  `agentCode` varchar(32) DEFAULT NULL,
  `sendCode` varchar(32) DEFAULT NULL,
  `trackingNo` varchar(32) DEFAULT NULL,
  `reqTime` varchar(32) DEFAULT NULL,
  `outAccount` varchar(32) DEFAULT NULL,
  `tradeAmount` varchar(32) DEFAULT NULL,
  `merCategory` varchar(32) DEFAULT NULL,
  `terminalType` varchar(32) DEFAULT NULL,
  `reqSysStance` varchar(32) DEFAULT NULL,
  `rawPayWay` varchar(32) DEFAULT NULL,
  `orderId` varchar(32) DEFAULT NULL,
  `patType` varchar(32) DEFAULT NULL,
  `rawReqSysStance` varchar(32) DEFAULT NULL,
  `rawReqTime` varchar(32) DEFAULT NULL,
  `tradeFee` varchar(32) DEFAULT NULL,
  `settlementAmount` varchar(32) DEFAULT NULL,
  `payWay` varchar(32) DEFAULT NULL,
  `merCode` varchar(32) DEFAULT NULL,
  `tradingType` varchar(32) DEFAULT NULL,
  `tradingAsType` varchar(32) DEFAULT NULL,
  `businessType` varchar(32) DEFAULT NULL,
  `accountType` varchar(32) DEFAULT NULL,
  `billType` varchar(32) DEFAULT NULL,
  `billNo` varchar(32) DEFAULT NULL,
  `interact` varchar(32) DEFAULT NULL,
  `rawReqSysStances` varchar(32) DEFAULT NULL,
  `merCodes` varchar(32) DEFAULT NULL,
  `bookedWay` varchar(32) DEFAULT NULL,
  `twoMercode` varchar(32) DEFAULT NULL,
  `twoMerAbbreviation` varchar(32) DEFAULT NULL,
  `twoMerAmount` varchar(32) DEFAULT NULL,
  `netAmount` varchar(32) DEFAULT NULL,
  `terminalNo` varchar(32) DEFAULT NULL,
  `mercustom` varchar(32) DEFAULT NULL,
  `preferentialAmount` varchar(32) DEFAULT NULL,
  `invoiceAmount` varchar(32) DEFAULT NULL,
  `keep` varchar(32) DEFAULT NULL,
  `dz_file_name` varchar(32) DEFAULT NULL,
  `inst_name` varchar(32) DEFAULT NULL,
  `bk_chk` int(11) DEFAULT NULL,
  `deduct_stlm_date` varchar(32) DEFAULT NULL,
  `whetherTk` tinyint(1) DEFAULT NULL,
  `process` varchar(32) DEFAULT NULL,
  `termId` varchar(32) DEFAULT NULL,
  `deductSysReference` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of duizhang_yl_wap_lst
-- ----------------------------
