CREATE TABLE `duizhang_upmp_lst` (
  `id` varchar(32) NOT NULL,
  `acqInstIdCode` varchar(11) NOT NULL,
  `fwdInstIdCode` varchar(11) NOT NULL,
  `reqSysStance` varchar(6) NOT NULL,
  `reqTime` varchar(20) NOT NULL,
  `outAccount` char(19) NOT NULL,
  `tradeAmount` varchar(12) NOT NULL,
  `portionAmount` char(12) DEFAULT NULL,
  `tradeFee` varchar(12) DEFAULT NULL,
  `msgType` char(4) NOT NULL,
  `process` varchar(6) DEFAULT NULL,
  `merType` char(4) DEFAULT NULL,
  `termId` varchar(8) NOT NULL,
  `merCode` varchar(16) NOT NULL,
  `deductSysReference` varchar(12) DEFAULT NULL,
  `reqType` char(2) NOT NULL,
  `authorizationCode` varchar(6) DEFAULT NULL,
  `rcvgInstIdCode` varchar(11) DEFAULT NULL,
  `origDataStance` char(6) DEFAULT NULL,
  `deductSysResponse` char(2) NOT NULL,
  `reqInputType` char(3) NOT NULL,
  `acceptorReceiveFee` varchar(12) DEFAULT NULL,
  `acceptorPayFee` varchar(12) DEFAULT NULL,
  `throughServiceFee` varchar(12) DEFAULT NULL,
  `convertShow` char(1) DEFAULT NULL,
  `cardNumber` char(3) DEFAULT NULL,
  `termReadAbility` char(1) DEFAULT NULL,
  `idConditionCode` char(1) DEFAULT NULL,
  `origDataTime` char(10) DEFAULT NULL,
  `issuingBankCode` varchar(11) DEFAULT NULL,
  `tradeAdress` char(1) DEFAULT NULL,
  `terminalType` char(2) DEFAULT NULL,
  `eci` varchar(2) DEFAULT NULL,
  `byStagesFee` varchar(11) DEFAULT NULL,
  `otherInfo` varchar(14) DEFAULT NULL,
  `whetherErroeHandle` int(11) NOT NULL DEFAULT '0',
  `dz_file_name` varchar(100) NOT NULL,
  `inst_name` varchar(64) NOT NULL,
  `bk_chk` int(11) NOT NULL DEFAULT '0',
  `deduct_stlm_date` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

