CREATE TABLE `original_szzh_lst` (
  `trade_id` varchar(32) NOT NULL,
  `terminal_id` varchar(64) DEFAULT NULL,
  `terminal_info` varchar(64) DEFAULT NULL,
  `terminal_type` smallint(6) DEFAULT NULL,
  `trade_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `out_account` varchar(64) DEFAULT NULL,
  `out_account_type` varchar(1) DEFAULT NULL,
  `out_acc_valid_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `out_account_info` varchar(512) DEFAULT NULL,
  `out_account_info2` varchar(512) DEFAULT NULL,
  `out_account_desc` varchar(512) DEFAULT NULL,
  `in_account` varchar(64) DEFAULT NULL,
  `in_card_name` varchar(8) DEFAULT NULL,
  `in_bank_id` varchar(30) DEFAULT NULL,
  `trade_amount` bigint(20) DEFAULT NULL,
  `trade_fee` varchar(40) DEFAULT NULL,
  `trade_currency` smallint(6) DEFAULT NULL,
  `trade_result` int(11) DEFAULT NULL,
  `req_sys_id` int(11) DEFAULT NULL,
  `req_sys_stance` varchar(32) DEFAULT NULL,
  `req_mer_code` varchar(32) DEFAULT NULL,
  `req_mer_term_id` varchar(16) DEFAULT NULL,
  `req_response` varchar(6) DEFAULT NULL,
  `deduct_sys_id` int(11) DEFAULT NULL,
  `deduct_sys_stance` varchar(32) DEFAULT NULL,
  `deduct_mer_code` varchar(32) DEFAULT NULL,
  `deduct_mer_term_id` varchar(16) DEFAULT NULL,
  `deduct_result` int(11) DEFAULT NULL,
  `deduct_sys_response` varchar(6) DEFAULT NULL,
  `deduct_roll_bk` tinyint(1) DEFAULT NULL,
  `deduct_roll_bk_result` smallint(6) DEFAULT NULL,
  `deduct_roll_bk_reason` varchar(6) DEFAULT NULL,
  `deduct_roll_bk_response` varchar(6) DEFAULT NULL,
  `deduct_roll_bk_stance` varchar(32) DEFAULT NULL,
  `trade_type` int(11) NOT NULL,
  `msg_num` int(11) DEFAULT NULL,
  `pass_wd_mode` varchar(32) DEFAULT NULL,
  `req_type` varchar(16) DEFAULT NULL,
  `req_input_type` varchar(16) DEFAULT NULL,
  `req_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `trade_req_method` varchar(11) DEFAULT NULL,
  `trade_desc` text,
  `in_account_type` int(11) DEFAULT NULL,
  `trade_other_info` varchar(600) DEFAULT NULL,
  `deduct_stlm_date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `deduct_sys_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `gain_sys_id` int(11) DEFAULT NULL,
  `gain_sys_stance` varchar(32) DEFAULT NULL,
  `gain_mer_code` varchar(32) DEFAULT NULL,
  `gain_mer_term_id` varchar(16) DEFAULT NULL,
  `gain_sys_response` varchar(6) DEFAULT NULL,
  `gain_result` int(11) DEFAULT NULL,
  `gain_trade_amount` bigint(20) DEFAULT NULL,
  `gain_sys_reference` varchar(12) DEFAULT NULL,
  `nii` varchar(3) DEFAULT NULL,
  `authorization_code` varchar(6) DEFAULT NULL,
  `additional_response_data` varchar(30) DEFAULT NULL,
  `additional_data` varchar(999) DEFAULT NULL,
  `boc` varchar(999) DEFAULT NULL,
  `custom_define_info` varchar(999) DEFAULT NULL,
  `original_trans_info` varchar(999) DEFAULT NULL,
  `req_process` varchar(6) DEFAULT NULL,
  `deduct_sys_reference` varchar(12) DEFAULT NULL,
  `trademsg_type` int(3) DEFAULT NULL,
  `deduct_rollbk_sys_reference` varchar(12) DEFAULT NULL,
  `mer_name` varchar(60) DEFAULT NULL,
  `bk_chk` int(11) NOT NULL DEFAULT '0',
  `whetherJs` tinyint(1) NOT NULL DEFAULT '0',
  `whetherValid` tinyint(1) NOT NULL DEFAULT '0',
  `whetherErroeHandle` int(11) NOT NULL DEFAULT '0',
  `whetherRiqie` tinyint(1) NOT NULL DEFAULT '0',
  `acqInstIdCode` varchar(8) NOT NULL,
  `fwdInstIdCode` varchar(8) NOT NULL,
  `deduct_rollbk_sys_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `agentId` varchar(6) NOT NULL,
  `whetherzero` char(1) NOT NULL,
  `whtherInnerJs` tinyint(1) NOT NULL DEFAULT '0',
  `ic_card_ser_no` char(3) DEFAULT NULL,
  `ic_read_and_condition` varchar(4) DEFAULT NULL,
  `whetherQs` tinyint(1) DEFAULT '0',
  `mer_fee` double(8,2) DEFAULT '0.00',
  `whetherTk` tinyint(1) DEFAULT '0',
  `zf_fee` double(8,2) DEFAULT '0.00',
  `zf_file_fee` varchar(12) DEFAULT '0',
  PRIMARY KEY (`trade_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

